#service:
#  name: user-thrift-service
#  port: 7911
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: 1234_qwer
#    url: jdbc:mysql://121.40.8.72:3306/jianshu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#    username: root1
