spring:
  profiles:
    active: dev

dubbo:
  scan:
    base-packages: com.juzhen.sale.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://42.192.76.49:8848
#    address: zookeeper://42.192.76.49:2181
#    address: zookeeper://localhost:2181
  application:
    qos:
      enable: false