spring:
  profiles:
    active: dev

dubbo:
  scan:
    base-packages: com.juzhen.sale.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost
  application:
    qos:
      enable: false