version: '3'

#networks:
#  default:
#    external:
#      name: imooc-network

services:
#  message-service:
#    image: message-service:latest

  user-service:
    image: 127.0.0.1:81/erp-service/user-service:1.0.5
    command:
    - "--mysql.address=42.193.7.166"
    - "--redis.address=42.192.76.49"
  user-http-service:
    image: 127.0.0.1:81/erp-service/user-http-service:latest
    links:
    - user-service
#    - message-service
    command:
    - "--redis.address=42.192.76.49"

#
#  sale-service:
#    image: 127.0.0.1:81/erp-service/sale-service:latest
#    links:
#    - user-service
#    command:
#    - "--mysql.address=42.193.7.166"
#    - "--redis.address=42.192.76.49"
#    - "--nacos.address=42.192.76.49"

  sale-edge-service:
    image: 127.0.0.1:81/erp-service/sale-edge-service:latest
    links:
    - user-http-service
#    - sale-service
    command:
    - "--nacos.address=42.192.76.49"
  api-gateway-zuul:
    image: 127.0.0.1:81/erp-service/api-gateway-zuul:latest
    links:
    - sale-edge-service
    - user-http-service
    ports:
    - 80:80