version: '3'

#networks:
#  default:
#    external:
#      name: imooc-network

services:
#  message-service:
#    image: message-service:latest

  user-service:
    image: user-service:latest
    command:
    - "--mysql.address=192.168.57.1"
    - "--redis.address=192.168.57.1"
  user-http-service:
    image: user-http-service:latest
    links:
    - user-service
#    - message-service
    command:
    - "--redis.address=192.168.57.1"

#
#  sale-service:
#    image: sale-service:latest
#    links:
#    - user-service
#    command:
#    - "--mysql.address=192.168.57.1"
#    - "--redis.address=192.168.57.1"
#    - "--nacos.address=192.168.57.1"

  sale-edge-service:
    image: sale-edge-service:latest
    links:
    - user-http-service
#    - sale-service
    command:
    - "--nacos.address=192.168.57.1"
  api-gateway-zuul:
    image: api-gateway-zuul:latest
    links:
    - sale-edge-service
    - user-http-service
    ports:
    - 80:80