spring:
  application:
    name: account-dubbo-service
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: ${provider.application.name}
  application:
    qos:
      enable: false
server:
  port: 8082

provider:
  application:
    name: sale-dubbo-service


thrift:
  message:
    ip: 127.0.0.1
    port: 9090
  user:
    ip: 127.0.0.1
    port: 7911
