spring:
  application:
    name: sale-edge-service
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: ${provider.application.name}
  application:
    qos:
      enable: false
server:
  port: 8082

provider:
  application:
    name: sale-dubbo-service


thrift:
  message:
    ip: message-service
    port: 9090
  user:
    ip: user-service
    port: 7911


user:
  edge:
    service:
      addr: user-http-service:8081